#!/usr/bin/env perl

use Modern::Perl;
use DBIx::Class::Schema::Loader 'make_schema_at';
use YAML qw/LoadFile/;

my $DEBUG = @ARGV and $ARGV[0] =~ /^\-[\-]*v/;

say $DBIx::Class::Schema::Loader::VERSION if $DEBUG;
my $config = LoadFile('etc/srvmanager.yml');

my @dsn = ($config->{database}->{dsn}, $config->{database}->{user}, $config->{database}->{password});

my $options = {
  debug          => $DEBUG,
  dump_directory => 'lib',
  components     => [qw/ InflateColumn::DateTime /],
  generate_pod   => 0,
};

make_schema_at(Schema => $options, \@dsn);

=head1 NAME

generate_dbic_schema

=head1 USAGE

perl generate_dbic_schema

=cut
